#!/bin/sh
# page-skeleton.sh — write the page's head, theme and script straight into the page, and
# hand the run only the markup half of the template.
#
#   page-skeleton.sh --out "$W/page.html" --title "Fix the invite gate"   # once, at stage 1
#   page-skeleton.sh --markup                                            # the design system, to read
#
#   --theme NAME   daylight | workshop | field-notes — one file under references/themes/. Rarely
#                  passed: the theme is the repository's decision, not the run's (see THE THEME).
#   --repo DIR     where to look for .accountable-review.yml (default: the git top level, else .)
#
# WHY THIS EXISTS. A page's head, its theme's token block and its script come to about 55 KB,
# which a run used to read into context only to type back out verbatim — paid once as resident
# context on every later request, and again as output tokens that then become
# context. It is the same rule step 9 already applies to excerpts: generate to a file and splice,
# never read the generated bytes back and retype them.
#
# The stronger reason is not tokens. Every colour on a published page — the light values, both dark
# blocks, the five --syn-* tints — lives in the head region and nowhere else. After this,
# no model declares one, so the half-declared-token defect that page-invariants.rb §6 and
# excerpts.rb exist to catch cannot be produced at all.
#
# THE TEMPLATE STAYS THE ONE SOURCE OF TRUTH. This script copies bytes out of it; it holds none of
# its own. tests/run.sh proves that by asserting the emitted head is an exact byte PREFIX of the
# template with its markers stripped, and the tail an exact byte SUFFIX — so inlining any CSS here
# fails immediately, and a marker moved in either file fails too. Extraction is an awk line range
# and nothing else: no printf reconstruction, no re-indentation, no round trip through $(…), which
# eats trailing newlines. The bytes must come out the way they went in.
#
# THE THEME. Three designs share one markup and differ only in fonts, tokens and a block of
# overrides, and each is a file under references/themes/. All of them replace the template's one
# SKELETON:THEME line, so the reader's appearance menu can switch between them, and ONE is active
# when the page opens — the repository's default. Which one is decided here, in this order: --theme, then
# ACCOUNTABLE_REVIEW_THEME (how ci/generate-review-map.sh passes the value it read from a --config
# file somewhere else), then review_map.theme in the repository's .accountable-review.yml, then
# daylight. The run is never asked: a theme is a team's choice of look, so it lives in the
# repository beside the team's other settings, and a reviewer gets the same page from CI and from
# their own terminal.
#
# This reads ONE key of that file and nothing else. setup-ci's read-config.sh owns the schema and
# validates it in CI, but this skill is installed alone by `npx skills add` and by Codex, where that
# script is not on disk — so the lookup is here, deliberately narrow, and a value with no theme file
# behind it is refused rather than defaulted: a team that wrote `theme: workshp` should hear about
# it, not get Daylight and wonder.
#
# Reads only, except for --out. Needs awk. No network.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TEMPLATE=$HERE/../references/page-template.html
THEMES=$HERE/../references/themes
OUT=; TITLE=; FORCE=; MARKUP=; THEME=; REPO=

HEAD_S='SKELETON:HEAD:START'; HEAD_E='SKELETON:HEAD:END'
TAIL_S='SKELETON:TAIL:START'; TAIL_E='SKELETON:TAIL:END'
THEME_M='SKELETON:THEME'
PLACEHOLDER='  <!-- SKELETON:BODY -- the run replaces this line with the rail, <main> and the sections. -->'

usage() { sed -n '2,${/^#/!q;s/^# \{0,1\}//;p;}' "$0"; }

while [ $# -gt 0 ]; do
  case $1 in
    --out)      OUT=${2:?--out needs a path}; shift 2 ;;
    --title)    TITLE=${2:?--title needs text}; shift 2 ;;
    --template) TEMPLATE=${2:?--template needs a path}; shift 2 ;;
    --themes)   THEMES=${2:?--themes needs a directory}; shift 2 ;;
    --theme)    THEME=${2:?--theme needs a name}; shift 2 ;;
    --repo)     REPO=${2:?--repo needs a directory}; shift 2 ;;
    --markup)   MARKUP=1; shift ;;
    --force)    FORCE=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) echo "page-skeleton.sh: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[ -r "$TEMPLATE" ] || { echo "page-skeleton.sh: cannot read template: $TEMPLATE" >&2; exit 2; }

# Every marker exactly once. A duplicate makes the range wrong and every other assertion still
# passes, which is the failure mode this repository keeps writing down.
for m in "$HEAD_S" "$HEAD_E" "$TAIL_S" "$TAIL_E" "$THEME_M"; do
  n=$(grep -c "$m" "$TEMPLATE" || true)
  [ "${n:-0}" -eq 1 ] || {
    echo "page-skeleton.sh: $TEMPLATE has $n lines matching $m, expected exactly 1" >&2; exit 1; }
done

# Strictly between the two marker lines: neither marker is emitted, so no published page carries
# a SKELETON string except the body placeholder, which the run replaces.
extract() {
  awk -v s="$1" -v e="$2" '
    index($0, s) { inside = 1; next }
    index($0, e) { inside = 0 }
    inside       { print }
  ' "$3"
}

if [ -n "$MARKUP" ]; then
  [ -z "$OUT" ] || { echo "page-skeleton.sh: --markup writes to stdout; drop --out" >&2; exit 2; }
  extract "$HEAD_E" "$TAIL_S" "$TEMPLATE"
  exit 0
fi

[ -n "$OUT" ]   || { echo "page-skeleton.sh: --out is required (or --markup)" >&2; exit 2; }
[ -n "$TITLE" ] || { echo "page-skeleton.sh: --title is required — a page titled {{PR_TITLE_OR_BRANCH}} Review is a defect the reader sees in their tab" >&2; exit 2; }

# The theme line must sit inside the HEAD range, or it would be dropped (outside every range) or
# handed to a run to read (in the markup half) — either way the page would carry no tokens at all.
n=$(extract "$HEAD_S" "$HEAD_E" "$TEMPLATE" | grep -c "$THEME_M" || true)
[ "${n:-0}" -eq 1 ] || {
  echo "page-skeleton.sh: $THEME_M must sit inside the HEAD range of $TEMPLATE" >&2; exit 1; }

# review_map.theme, and only that: the first-level key under review_map:, so a `theme:` nested
# deeper (under delivery:) is not mistaken for it. Quotes and a trailing comment are stripped the
# way read-config.sh strips them.
config_theme() {
  awk '
    { sub(/\r$/, "") }
    /^[[:space:]]*(#|$)/ { next }
    /^[^[:space:]]/ { inmap = ($0 ~ /^review_map:[[:space:]]*(#.*)?$/); depth = 0; next }
    inmap {
      match($0, /^[[:space:]]*/)
      if (depth == 0) depth = RLENGTH
      if (RLENGTH != depth || $0 !~ /^[[:space:]]*theme:/) next
      v = $0; sub(/^[[:space:]]*theme:[[:space:]]*/, "", v)
      if (v !~ /^["\047]/) sub(/[[:space:]]+#.*$/, "", v)
      sub(/[[:space:]]+$/, "", v)
      if (v ~ /^".*"$/ || v ~ /^\047.*\047$/) v = substr(v, 2, length(v) - 2)
      print v; exit
    }
  ' "$1"
}

SOURCE=--theme
if [ -z "$THEME" ] && [ -n "${ACCOUNTABLE_REVIEW_THEME:-}" ]; then
  THEME=$ACCOUNTABLE_REVIEW_THEME; SOURCE=ACCOUNTABLE_REVIEW_THEME
fi
if [ -z "$THEME" ]; then
  [ -n "$REPO" ] || REPO=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
  if [ -f "$REPO/.accountable-review.yml" ]; then
    THEME=$(config_theme "$REPO/.accountable-review.yml")
    SOURCE="review_map.theme in $REPO/.accountable-review.yml"
  fi
fi
[ -n "$THEME" ] || { THEME=daylight; SOURCE=default; }

THEME_FILE=$THEMES/$THEME.html
case $THEME in
  *[!a-z0-9-]*|-*) THEME_FILE= ;;
esac
if [ -z "$THEME_FILE" ] || [ ! -r "$THEME_FILE" ]; then
  have=$(ls "$THEMES" 2>/dev/null | sed -n 's/\.html$//p' | tr '\n' ' ')
  echo "page-skeleton.sh: no theme named '$THEME' (from $SOURCE); themes: ${have:-none found in $THEMES}" >&2
  exit 2
fi

# Three states, the way install-workflow.sh has them. The third exists for the one catastrophic
# error this design makes possible: a confused run re-invoking the skeleton at stage 3 and wiping
# sections that are already published.
if [ -e "$OUT" ] && [ -z "$FORCE" ]; then
  if ! grep -q 'SKELETON:BODY' "$OUT"; then
    echo "page-skeleton.sh: $OUT already has content written into it — refusing to overwrite." >&2
    echo "  The skeleton is written ONCE, at the start of stage 1. If a page is being staged, this" >&2
    echo "  call would discard what is already published. --force only if that is what you mean." >&2
    exit 3
  fi
fi

# & first, or the entities it introduces get escaped again.
esc=$(printf '%s' "$TITLE" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g')

tmp=$OUT.skeleton.$$
themes=$OUT.themes.$$
trap 'rm -f "$tmp" "$themes"' EXIT INT HUP TERM

# EVERY theme goes onto the page, so the appearance menu can switch without a second file; the
# chosen one is active and the rest carry media="not all" on each element that names them. The
# order is the menu's: the three this repository ships first, as the design lays them out, then
# any other file in the directory alphabetically, so a theme added later appears without an edit
# here. A theme file's elements are found by their data-style attribute and nothing else.
: > "$themes"; done_names=
for name in daylight workshop field-notes $(ls "$THEMES" | sed -n 's/\.html$//p' | sort); do
  case " $done_names " in *" $name "*) continue ;; esac
  [ -r "$THEMES/$name.html" ] || continue
  done_names="$done_names $name"
  if [ "$name" = "$THEME" ]; then
    cat "$THEMES/$name.html" >> "$themes"
  else
    awk -v a="data-style=\"$name\"" '
      { out = ""; rest = $0
        while ((p = index(rest, a)) > 0) {
          out = out substr(rest, 1, p - 1 + length(a)) " media=\"not all\""
          rest = substr(rest, p + length(a))
        }
        print out rest }' "$THEMES/$name.html" >> "$themes"
  fi
done

# Substituted by index rather than by gsub, because an & in a title is ordinary and awk's gsub
# would read it as "the whole match".
extract "$HEAD_S" "$HEAD_E" "$TEMPLATE" | awk -v t="$esc" -v m="$THEME_M" -v theme="$themes" '
  index($0, m) { while ((getline l < theme) > 0) print l; close(theme); next }
  { k = "{{PR_TITLE_OR_BRANCH}}"; p = index($0, k)
    if (p > 0) $0 = substr($0, 1, p - 1) t substr($0, p + length(k))
    print }' > "$tmp"
# The <title> must be the page's first line. The Artifact gallery names a page from its <title>,
# and with the template's 11 KB header comment above it the gallery missed it and fell back to
# the file name, so every Review Map was listed as "page". So the line sits first in the HEAD
# range, and this refuses to write a page where it does not, rather than publish one more
# untitled map.
case $(sed -n '1p' "$tmp") in
  '<title>'*) ;;
  *) echo "page-skeleton.sh: the template's HEAD range must open with <title>, or the published page is listed under its file name" >&2; exit 1 ;;
esac
printf '%s\n' "$PLACEHOLDER" >> "$tmp"
extract "$TAIL_S" "$TAIL_E" "$TEMPLATE" >> "$tmp"

mv "$tmp" "$OUT"
rm -f "$themes"
trap - EXIT INT HUP TERM
echo "page-skeleton.sh: wrote $(wc -c < "$OUT" | tr -d ' ') bytes to $OUT (theme: $THEME)"
