#!/bin/sh
# page-skeleton.sh — write the page's head, token block and script straight into the page, and
# hand the run only the markup half of the template.
#
#   page-skeleton.sh --out "$W/page.html" --title "Fix the invite gate"   # once, at stage 1
#   page-skeleton.sh --markup --level brief                              # the design system, to read
#   page-skeleton.sh --markup                                            # ... every level of it
#
# WHY THIS EXISTS. references/page-template.html is 107 KB, and 54.5 KB of that is a head, a token
# block and a script that a run used to read into context only to type back out verbatim — paid
# once as resident context on every later request, and again as output tokens that then become
# context. It is the same rule step 9 already applies to excerpts: generate to a file and splice,
# never read the generated bytes back and retype them.
#
# The stronger reason is not tokens. Every colour on a published page — the light values, both dark
# blocks, --rails, the four --syn-* tints — lives in the head region and nowhere else. After this,
# no model declares one, so the half-declared-token defect that page-invariants.rb §6 and
# excerpts.rb exist to catch cannot be produced at all.
#
# THE TEMPLATE STAYS THE ONE SOURCE OF TRUTH. This script copies bytes out of it; it holds none of
# its own. tests/run.sh proves that by asserting the emitted head is an exact byte PREFIX of the
# template with its markers stripped, and the tail an exact byte SUFFIX — so inlining any CSS here
# fails immediately, and a marker moved in either file fails too. Extraction is an awk line range
# and nothing else: no printf reconstruction, no re-indentation, no round trip through $(…), which
# eats trailing newlines. The bytes must come out the way they went in.
#
# --LEVEL DROPS WHAT THIS RUN CANNOT WRITE. Sections 4 to 7 and the merged brief section are
# two renderings of the same tail, and so is the rail below 03: a run writes one of each and was
# being handed both. SKELETON:ONLY:level=<brief|full> pairs in the markup half mark them, and
# --level keeps its own and drops the other -- 18 KB at --brief, 8 KB at --full, off a half that
# is resident for every request after step 9. Bare --markup keeps everything and only strips the
# markers, so tests/run.sh and the eval drivers read exactly the bytes they read before.
#
# It is subtractive and fails closed. Filtering only ever removes whole marked regions, never
# rewrites a line; an unpaired marker, a nested pair, an unknown tag or a tag with no region at
# all exits non-zero, because each of those would otherwise silently drop or silently keep a
# section and the page would still look finished. A rule that passes is not a rule that looked.
#
# Reads only, except for --out. Needs awk. No network.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TEMPLATE=$HERE/../references/page-template.html
OUT=; TITLE=; FORCE=; MARKUP=; LEVEL=

# The tag vocabulary. A tag outside it is a typo, and a typo that meant "never dropped"
# would be invisible on a page that still looked finished.
ONLY_TAGS='level=brief level=full'

HEAD_S='SKELETON:HEAD:START'; HEAD_E='SKELETON:HEAD:END'
TAIL_S='SKELETON:TAIL:START'; TAIL_E='SKELETON:TAIL:END'
PLACEHOLDER='  <!-- SKELETON:BODY -- the run replaces this line with the rail, <main> and the sections. -->'

usage() { sed -n '2,${/^#/!q;s/^# \{0,1\}//;p;}' "$0"; }

while [ $# -gt 0 ]; do
  case $1 in
    --out)      OUT=${2:?--out needs a path}; shift 2 ;;
    --title)    TITLE=${2:?--title needs text}; shift 2 ;;
    --template) TEMPLATE=${2:?--template needs a path}; shift 2 ;;
    --markup)   MARKUP=1; shift ;;
    --level)    LEVEL=${2:?--level needs brief or full}; shift 2 ;;
    --force)    FORCE=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) echo "page-skeleton.sh: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[ -r "$TEMPLATE" ] || { echo "page-skeleton.sh: cannot read template: $TEMPLATE" >&2; exit 2; }

# Every marker exactly once. A duplicate makes the range wrong and every other assertion still
# passes, which is the failure mode this repository keeps writing down.
for m in "$HEAD_S" "$HEAD_E" "$TAIL_S" "$TAIL_E"; do
  n=$(grep -c "$m" "$TEMPLATE" || true)
  [ "${n:-0}" -eq 1 ] || {
    echo "page-skeleton.sh: $TEMPLATE has $n lines matching $m, expected exactly 1" >&2; exit 1; }
done

case ${LEVEL:-} in
  ''|brief|full) ;;
  *) echo "page-skeleton.sh: --level takes brief or full, not '$LEVEL'" >&2
     echo "  --review is not a level this reaches: the skill stops at that level before step 9." >&2
     exit 2 ;;
esac

# --level shapes the half a run READS. The head and tail hold no section and no rail, so a level
# there would be a flag that quietly did nothing -- which is worse than a refusal.
if [ -n "$LEVEL" ] && [ -z "$MARKUP" ]; then
  echo "page-skeleton.sh: --level only applies to --markup; the emitted head and tail carry no section" >&2
  exit 2
fi

# Every ONLY region is paired, unnested, and tagged from the vocabulary above; every tag in that
# vocabulary has at least one region. Each of these is a way to drop or keep a whole section
# while every other assertion still passes.
# A MARKER IS A WHOLE ONE-LINE COMMENT, matched strictly. Anything looser reads the maintainer
# note that documents these markers as a marker -- which is what the first version did, and is
# this repository's recurring shape: the prose quotes the thing the rule is about.
only_report=$(awk -v tags="$ONLY_TAGS" '
  BEGIN { n = split(tags, t, " "); for (i = 1; i <= n; i++) known[t[i]] = 1 }
  /^[ \t]*<!-- SKELETON:ONLY:[^ ]+:(START|END) -->[ \t]*$/ {
    line = $0
    sub(/^[ \t]*<!-- SKELETON:ONLY:/, "", line); sub(/ -->[ \t]*$/, "", line)
    isend = (line ~ /:END$/)
    tag = line; sub(/:(START|END)$/, "", tag)
    if (!(tag in known)) { print "unknown tag \"" tag "\" at line " NR; next }
    seen[tag] = 1
    if (isend) {
      if (open != tag) { print "unmatched END for \"" tag "\" at line " NR; bad = 1 }
      open = ""
    } else {
      if (open != "") { print "region \"" tag "\" at line " NR " nests inside \"" open "\""; bad = 1 }
      open = tag
    }
  }
  END {
    if (open != "") print "region \"" open "\" is never closed"
    for (i = 1; i <= n; i++) if (!(t[i] in seen)) print "no region is tagged \"" t[i] "\""
  }
' "$TEMPLATE")
[ -z "$only_report" ] || {
  echo "page-skeleton.sh: $TEMPLATE has malformed SKELETON:ONLY markers:" >&2
  printf '  %s\n' "$only_report" >&2
  exit 1; }

# Strictly between the two marker lines: neither marker is emitted, so no published page carries
# a SKELETON string except the body placeholder, which the run replaces.
extract() {
  awk -v s="$1" -v e="$2" '
    index($0, s) { inside = 1; next }
    index($0, e) { inside = 0 }
    inside       { print }
  ' "$3"
}

# Drops the regions tagged for a level other than $KEEP and prints no marker line in any mode,
# so bare --markup is the markup half exactly as it was before levels existed. Subtractive by
# construction: the only actions are "print this line" and "do not".
only_filter() {
  awk -v keep="$1" '
    /^[ \t]*<!-- SKELETON:ONLY:[^ ]+:(START|END) -->[ \t]*$/ {
      line = $0
      sub(/^[ \t]*<!-- SKELETON:ONLY:/, "", line); sub(/ -->[ \t]*$/, "", line)
      tag = line; sub(/:(START|END)$/, "", tag)
      if (line ~ /:END$/) drop = 0
      else if (keep != "" && tag != "level=" keep) drop = 1
      next
    }
    !drop { print }
  '
}

if [ -n "$MARKUP" ]; then
  [ -z "$OUT" ] || { echo "page-skeleton.sh: --markup writes to stdout; drop --out" >&2; exit 2; }
  extract "$HEAD_E" "$TAIL_S" "$TEMPLATE" | only_filter "$LEVEL"
  exit 0
fi

[ -n "$OUT" ]   || { echo "page-skeleton.sh: --out is required (or --markup)" >&2; exit 2; }
[ -n "$TITLE" ] || { echo "page-skeleton.sh: --title is required — a page titled {{PR_TITLE_OR_BRANCH}} Review is a defect the reader sees in their tab" >&2; exit 2; }

# Three states, the way install-workflow.sh has them. The third exists for the one catastrophic
# error this design makes possible: a confused run re-invoking the skeleton at stage 3 and wiping
# sections that are already published.
if [ -e "$OUT" ] && [ -z "$FORCE" ]; then
  if ! grep -q 'SKELETON:BODY' "$OUT"; then
    echo "page-skeleton.sh: $OUT already has content written into it — refusing to overwrite." >&2
    echo "  The skeleton is written ONCE, at the start of stage 1. If a page is being staged, this" >&2
    echo "  call would discard what is already published. --force only if that is what you mean." >&2
    exit 3
  fi
fi

# & first, or the entities it introduces get escaped again.
esc=$(printf '%s' "$TITLE" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g')

tmp=$OUT.skeleton.$$
trap 'rm -f "$tmp"' EXIT INT HUP TERM

# Substituted by index rather than by gsub, because an & in a title is ordinary and awk's gsub
# would read it as "the whole match".
extract "$HEAD_S" "$HEAD_E" "$TEMPLATE" | awk -v t="$esc" '
  { k = "{{PR_TITLE_OR_BRANCH}}"; p = index($0, k)
    if (p > 0) $0 = substr($0, 1, p - 1) t substr($0, p + length(k))
    print }' > "$tmp"
printf '%s\n' "$PLACEHOLDER" >> "$tmp"
extract "$TAIL_S" "$TAIL_E" "$TEMPLATE" >> "$tmp"

mv "$tmp" "$OUT"
trap - EXIT INT HUP TERM
echo "page-skeleton.sh: wrote $(wc -c < "$OUT" | tr -d ' ') bytes to $OUT"
