#!/bin/sh
# page-skeleton.sh — write the page's head, token block and script straight into the page, and
# hand the run only the markup half of the template.
#
#   page-skeleton.sh --out "$W/page.html" --title "Fix the invite gate"   # once, at stage 1
#   page-skeleton.sh --markup                                            # the design system, to read
#
# WHY THIS EXISTS. references/page-template.html is 107 KB, and 54.5 KB of that is a head, a token
# block and a script that a run used to read into context only to type back out verbatim — paid
# once as resident context on every later request, and again as output tokens that then become
# context. It is the same rule step 9 already applies to excerpts: generate to a file and splice,
# never read the generated bytes back and retype them.
#
# The stronger reason is not tokens. Every colour on a published page — the light values, both dark
# blocks, the five --syn-* tints — lives in the head region and nowhere else. After this,
# no model declares one, so the half-declared-token defect that page-invariants.rb §6 and
# excerpts.rb exist to catch cannot be produced at all.
#
# THE TEMPLATE STAYS THE ONE SOURCE OF TRUTH. This script copies bytes out of it; it holds none of
# its own. tests/run.sh proves that by asserting the emitted head is an exact byte PREFIX of the
# template with its markers stripped, and the tail an exact byte SUFFIX — so inlining any CSS here
# fails immediately, and a marker moved in either file fails too. Extraction is an awk line range
# and nothing else: no printf reconstruction, no re-indentation, no round trip through $(…), which
# eats trailing newlines. The bytes must come out the way they went in.
#
# Reads only, except for --out. Needs awk. No network.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TEMPLATE=$HERE/../references/page-template.html
OUT=; TITLE=; FORCE=; MARKUP=

HEAD_S='SKELETON:HEAD:START'; HEAD_E='SKELETON:HEAD:END'
TAIL_S='SKELETON:TAIL:START'; TAIL_E='SKELETON:TAIL:END'
PLACEHOLDER='  <!-- SKELETON:BODY -- the run replaces this line with the rail, <main> and the sections. -->'

usage() { sed -n '2,${/^#/!q;s/^# \{0,1\}//;p;}' "$0"; }

while [ $# -gt 0 ]; do
  case $1 in
    --out)      OUT=${2:?--out needs a path}; shift 2 ;;
    --title)    TITLE=${2:?--title needs text}; shift 2 ;;
    --template) TEMPLATE=${2:?--template needs a path}; shift 2 ;;
    --markup)   MARKUP=1; shift ;;
    --force)    FORCE=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) echo "page-skeleton.sh: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[ -r "$TEMPLATE" ] || { echo "page-skeleton.sh: cannot read template: $TEMPLATE" >&2; exit 2; }

# Every marker exactly once. A duplicate makes the range wrong and every other assertion still
# passes, which is the failure mode this repository keeps writing down.
for m in "$HEAD_S" "$HEAD_E" "$TAIL_S" "$TAIL_E"; do
  n=$(grep -c "$m" "$TEMPLATE" || true)
  [ "${n:-0}" -eq 1 ] || {
    echo "page-skeleton.sh: $TEMPLATE has $n lines matching $m, expected exactly 1" >&2; exit 1; }
done

# Strictly between the two marker lines: neither marker is emitted, so no published page carries
# a SKELETON string except the body placeholder, which the run replaces.
extract() {
  awk -v s="$1" -v e="$2" '
    index($0, s) { inside = 1; next }
    index($0, e) { inside = 0 }
    inside       { print }
  ' "$3"
}

if [ -n "$MARKUP" ]; then
  [ -z "$OUT" ] || { echo "page-skeleton.sh: --markup writes to stdout; drop --out" >&2; exit 2; }
  extract "$HEAD_E" "$TAIL_S" "$TEMPLATE"
  exit 0
fi

[ -n "$OUT" ]   || { echo "page-skeleton.sh: --out is required (or --markup)" >&2; exit 2; }
[ -n "$TITLE" ] || { echo "page-skeleton.sh: --title is required — a page titled {{PR_TITLE_OR_BRANCH}} Review is a defect the reader sees in their tab" >&2; exit 2; }

# Three states, the way install-workflow.sh has them. The third exists for the one catastrophic
# error this design makes possible: a confused run re-invoking the skeleton at stage 3 and wiping
# sections that are already published.
if [ -e "$OUT" ] && [ -z "$FORCE" ]; then
  if ! grep -q 'SKELETON:BODY' "$OUT"; then
    echo "page-skeleton.sh: $OUT already has content written into it — refusing to overwrite." >&2
    echo "  The skeleton is written ONCE, at the start of stage 1. If a page is being staged, this" >&2
    echo "  call would discard what is already published. --force only if that is what you mean." >&2
    exit 3
  fi
fi

# & first, or the entities it introduces get escaped again.
esc=$(printf '%s' "$TITLE" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g')

tmp=$OUT.skeleton.$$
trap 'rm -f "$tmp"' EXIT INT HUP TERM

# Substituted by index rather than by gsub, because an & in a title is ordinary and awk's gsub
# would read it as "the whole match".
extract "$HEAD_S" "$HEAD_E" "$TEMPLATE" | awk -v t="$esc" '
  { k = "{{PR_TITLE_OR_BRANCH}}"; p = index($0, k)
    if (p > 0) $0 = substr($0, 1, p - 1) t substr($0, p + length(k))
    print }' > "$tmp"
printf '%s\n' "$PLACEHOLDER" >> "$tmp"
extract "$TAIL_S" "$TAIL_E" "$TEMPLATE" >> "$tmp"

mv "$tmp" "$OUT"
trap - EXIT INT HUP TERM
echo "page-skeleton.sh: wrote $(wc -c < "$OUT" | tr -d ' ') bytes to $OUT"
