#!/bin/sh
# render-workflow.sh — render the Accountable Review GitHub Actions workflow.
#
#   Usage: render-workflow.sh [--plugin-repo owner/repo] [--plugin-ref TAG]
#                             [--claude-code-version SPEC] [--node-version N]
#                             [--timeout-minutes N]
#                             [--regenerate-on-push | --no-regenerate-on-push]
#                             [--skip-authors a,b | --no-skip-authors]
#                             [--min-files N] [--min-lines N]
#                             [--size-gate | --no-size-gate]
#                             [--pr-comment | --no-pr-comment]
#
# Prints the workflow YAML on stdout. It reads nothing from the repository being
# set up and asks nothing: the same flags always produce the same bytes, which is
# what makes install-workflow.sh able to tell "already set up" from "edited by
# hand" by comparing rather than by parsing.
#
# THE SUBSTITUTIONS FALL INTO TWO KINDS, and the difference decides what happens
# when setup is run a second time.
#
# The first four — which plugin, which ref, which Claude Code, which Node — say
# what runs. A re-run re-derives them, because moving the version pin is the
# reason to re-run at all.
#
# The rest are decisions a person confirmed during setup, and a re-run must not
# quietly revert them — the rendered file records them in a `# Decisions:` line
# and install-workflow.sh reads that back. They are of two kinds:
#
#   WHEN a Review Map is generated — the push trigger, the bot authors, the size
#   gate and its two numbers. Each decides whether a model run happens.
#
#   WHETHER the link is commented on the pull request. It is the only decision
#   here that changes what the job is permitted to do, since the comment is what
#   `pull-requests: write` is for. Off, and neither the step nor the permission
#   is rendered — a repository does not grant a write scope for a step it does
#   not have.
#
# That is the whole knob set, and the test any addition has to pass is that it
# decides whether a run happens or what the job may do. The draft guard, the fork
# guard, the concurrency group and `contents: read` have no flag, because a knob
# on each is a way to end up generating Review Maps for draft pull requests or
# handing this job write access it does not use. And what a team configures about
# the map itself — the effort, the delivery provider, the retention — is read from
# .accountable-review.yml at RUN time by the scripts the workflow calls, so
# changing it never means regenerating this file.

set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SKILL_DIR=$(dirname "$HERE")
PLUGIN_ROOT=$(dirname "$(dirname "$SKILL_DIR")")
TEMPLATE=$SKILL_DIR/templates/workflow.yml

PLUGIN_REPO=wyeworks/accountable-review
PLUGIN_REF=
CLAUDE_CODE_VERSION=2
NODE_VERSION=22
TIMEOUT_MINUTES=30

# The confirmed defaults. Regenerating on every push is off, so a pull request
# gets one Review Map; bots are skipped; a change small on every axis is skipped;
# and the link is commented on the pull request, because a map nobody can find is
# a map nobody reads. Each is explained where it lands, in templates/workflow.yml.
PUSH=0
SKIP_AUTHORS='dependabot[bot]'
SIZE_GATE=1
MIN_FILES=2
MIN_LINES=50
PR_COMMENT=1

while [ $# -gt 0 ]; do
  case $1 in
    --plugin-repo)          PLUGIN_REPO=$2;         shift 2 ;;
    --plugin-ref)           PLUGIN_REF=$2;          shift 2 ;;
    --claude-code-version)  CLAUDE_CODE_VERSION=$2; shift 2 ;;
    --node-version)         NODE_VERSION=$2;        shift 2 ;;
    --timeout-minutes)      TIMEOUT_MINUTES=$2;     shift 2 ;;
    --regenerate-on-push)    PUSH=1; shift ;;
    --no-regenerate-on-push) PUSH=0; shift ;;
    --skip-authors)         SKIP_AUTHORS=$2; shift 2 ;;
    --no-skip-authors)      SKIP_AUTHORS=;   shift ;;
    --min-files)            MIN_FILES=$2; SIZE_GATE=1; shift 2 ;;
    --min-lines)            MIN_LINES=$2; SIZE_GATE=1; shift 2 ;;
    --size-gate)            SIZE_GATE=1; shift ;;
    --no-size-gate)         SIZE_GATE=0; shift ;;
    --pr-comment)           PR_COMMENT=1; shift ;;
    --no-pr-comment)        PR_COMMENT=0; shift ;;
    --template)             TEMPLATE=$2;            shift 2 ;;
    -h|--help) sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "render-workflow.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

# The default ref is this plugin's own release tag — the one `claude plugin tag`
# creates — so a workflow generated by version 0.15.0 pins version 0.15.0 rather
# than whatever main happens to hold the day it runs. `claude plugin install` has
# no version argument, which is why the workflow clones a tag instead.
if [ -z "$PLUGIN_REF" ]; then
  version=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
    "$PLUGIN_ROOT/.claude-plugin/plugin.json" 2>/dev/null | head -n 1)
  [ -n "$version" ] || {
    echo "render-workflow.sh: cannot read the plugin version from $PLUGIN_ROOT/.claude-plugin/plugin.json" >&2
    echo "Pass --plugin-ref explicitly." >&2
    exit 1
  }
  PLUGIN_REF="accountable-review--v$version"
fi

[ -r "$TEMPLATE" ] || { echo "render-workflow.sh: cannot read $TEMPLATE" >&2; exit 1; }

for v in "$PLUGIN_REPO" "$PLUGIN_REF" "$CLAUDE_CODE_VERSION" "$NODE_VERSION" "$TIMEOUT_MINUTES"; do
  case $v in
    *[!A-Za-z0-9._/@^~-]*|'')
      echo "render-workflow.sh: refusing to substitute '$v' — it would need quoting in YAML." >&2
      exit 1 ;;
  esac
done

# The two thresholds go into an expression GitHub parses, so a non-integer is not
# a formatting problem — it is a workflow file that is rejected outright, with no
# job created and an error that does not name the line.
for v in "$MIN_FILES" "$MIN_LINES"; do
  case $v in
    *[!0-9]*|'')
      echo "render-workflow.sh: --min-files and --min-lines take a whole number, not '$v'." >&2
      exit 1 ;;
  esac
done

# Author logins carry the brackets of `dependabot[bot]`, so they get their own
# rule rather than the YAML-safety one above. They land inside single quotes in
# the expression, so a quote is refused rather than escaped — and the check is a
# subtraction rather than a shell bracket expression, because `[` and `]` are the
# two characters a bracket expression is worst at matching literally.
if [ -n "$SKIP_AUTHORS" ]; then
  leftover=$(printf '%s' "$SKIP_AUTHORS" | tr -d 'A-Za-z0-9._/@,[]-')
  if [ -n "$leftover" ]; then
    echo "render-workflow.sh: refusing to substitute the author list '$SKIP_AUTHORS'" >&2
    echo "— it contains characters a quoted login may not carry." >&2
    exit 1
  fi
fi

# The canonical, complete form of every confirmed decision, always printed in the
# same order whatever order the flags arrived in — install-workflow.sh reads this
# line back, so it has to round-trip exactly rather than record only what differs.
DECISIONS=
if [ "$PUSH" = 1 ]; then
  DECISIONS="--regenerate-on-push"
else
  DECISIONS="--no-regenerate-on-push"
fi
if [ -n "$SKIP_AUTHORS" ]; then
  DECISIONS="$DECISIONS --skip-authors $SKIP_AUTHORS"
else
  DECISIONS="$DECISIONS --no-skip-authors"
fi
if [ "$SIZE_GATE" = 1 ]; then
  DECISIONS="$DECISIONS --min-files $MIN_FILES --min-lines $MIN_LINES"
else
  DECISIONS="$DECISIONS --no-size-gate"
fi
if [ "$PR_COMMENT" = 1 ]; then
  DECISIONS="$DECISIONS --pr-comment"
else
  DECISIONS="$DECISIONS --no-pr-comment"
fi

# Blocks first, then scalars. A `SETUP:IF:<name>` line opens a block and
# `SETUP:END:<name>` closes it; the block survives only if its name is on, and
# the marker lines never reach the output either way. One marker per line, like
# the review-map skeleton's, because extraction is a line test.
#
# The author list crosses into awk as the comma-separated string rather than as
# the rendered lines: a `-v` value containing a newline is a hard error in the awk
# that ships with macOS, and building the clauses on this side would be the
# obvious way to hit it. One `&&` clause per author, each on its own line at the
# expression's one indentation — a list rather than a single
# `contains(fromJSON(...))` call, so the reader of a rejected workflow file can
# see which line is which.
awk -v push="$PUSH" -v logins="$SKIP_AUTHORS" -v size="$SIZE_GATE" -v comment="$PR_COMMENT" '
  BEGIN {
    on["push"]       = push
    on["no-push"]    = push ? 0 : 1
    on["authors"]    = (logins == "") ? 0 : 1
    on["size"]       = size
    on["comment"]    = comment
    on["no-comment"] = comment ? 0 : 1
    depth = 0
  }
  /^[[:space:]]*# SETUP:IF:/ {
    name = $0; sub(/^.*# SETUP:IF:/, "", name); sub(/[[:space:]]*$/, "", name)
    if (!(name in on)) { print "render-workflow.sh: unknown SETUP block: " name > "/dev/stderr"; exit 1 }
    depth++
    if (!on[name]) skipping = depth
    next
  }
  /^[[:space:]]*# SETUP:END:/ {
    if (skipping == depth) skipping = 0
    depth--
    next
  }
  skipping { next }
  $0 == "{{AUTHOR_CLAUSES}}" {
    n = split(logins, a, ",")
    for (i = 1; i <= n; i++)
      if (a[i] != "")
        print "      && github.event.pull_request.user.login != \x27" a[i] "\x27"
    next
  }
  { print }
  END { if (depth != 0) { print "render-workflow.sh: unclosed SETUP block in the template" > "/dev/stderr"; exit 1 } }
' "$TEMPLATE" |
sed \
  -e "s|{{PLUGIN_REPO}}|$PLUGIN_REPO|g" \
  -e "s|{{PLUGIN_REF}}|$PLUGIN_REF|g" \
  -e "s|{{CLAUDE_CODE_VERSION}}|$CLAUDE_CODE_VERSION|g" \
  -e "s|{{NODE_VERSION}}|$NODE_VERSION|g" \
  -e "s|{{TIMEOUT_MINUTES}}|$TIMEOUT_MINUTES|g" \
  -e "s|{{DECISIONS}}|$DECISIONS|g" \
  -e "s|{{MIN_FILES}}|$MIN_FILES|g" \
  -e "s|{{MIN_LINES}}|$MIN_LINES|g"
