#!/bin/sh
# render-workflow.sh — render the Accountable Review GitHub Actions workflow.
#
#   Usage: render-workflow.sh [--plugin-repo owner/repo] [--plugin-ref TAG]
#                             [--claude-code-version SPEC] [--node-version N]
#                             [--timeout-minutes N]
#
# Prints the workflow YAML on stdout. It reads nothing from the repository being
# set up and asks nothing: the same flags always produce the same bytes, which is
# what makes install-workflow.sh able to tell "already set up" from "edited by
# hand" by comparing rather than by parsing.
#
# Almost nothing is substituted, and that is deliberate. The triggers, the draft
# guard, the concurrency group and the permissions are not configuration — they
# are the design, and a knob on each would be a way to end up with a setup that
# generates Review Maps for draft PRs. What a team does configure — the detail
# level, the effort, the delivery provider, the retention — is read from
# .accountable-review.yml at RUN time by the scripts the workflow calls, so
# changing it does not mean regenerating this file. The four substitutions here
# are the ones that cannot work that way: which version of the plugin runs, and
# what it runs on.

set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SKILL_DIR=$(dirname "$HERE")
PLUGIN_ROOT=$(dirname "$(dirname "$SKILL_DIR")")
TEMPLATE=$SKILL_DIR/templates/workflow.yml

PLUGIN_REPO=wyeworks/accountable-review
PLUGIN_REF=
CLAUDE_CODE_VERSION=2
NODE_VERSION=22
TIMEOUT_MINUTES=30

while [ $# -gt 0 ]; do
  case $1 in
    --plugin-repo)          PLUGIN_REPO=$2;         shift 2 ;;
    --plugin-ref)           PLUGIN_REF=$2;          shift 2 ;;
    --claude-code-version)  CLAUDE_CODE_VERSION=$2; shift 2 ;;
    --node-version)         NODE_VERSION=$2;        shift 2 ;;
    --timeout-minutes)      TIMEOUT_MINUTES=$2;     shift 2 ;;
    --template)             TEMPLATE=$2;            shift 2 ;;
    -h|--help) sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "render-workflow.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

# The default ref is this plugin's own release tag — the one `claude plugin tag`
# creates — so a workflow generated by version 0.15.0 pins version 0.15.0 rather
# than whatever main happens to hold the day it runs. `claude plugin install` has
# no version argument, which is why the workflow clones a tag instead.
if [ -z "$PLUGIN_REF" ]; then
  version=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
    "$PLUGIN_ROOT/.claude-plugin/plugin.json" 2>/dev/null | head -n 1)
  [ -n "$version" ] || {
    echo "render-workflow.sh: cannot read the plugin version from $PLUGIN_ROOT/.claude-plugin/plugin.json" >&2
    echo "Pass --plugin-ref explicitly." >&2
    exit 1
  }
  PLUGIN_REF="accountable-review--v$version"
fi

[ -r "$TEMPLATE" ] || { echo "render-workflow.sh: cannot read $TEMPLATE" >&2; exit 1; }

for v in "$PLUGIN_REPO" "$PLUGIN_REF" "$CLAUDE_CODE_VERSION" "$NODE_VERSION" "$TIMEOUT_MINUTES"; do
  case $v in
    *[!A-Za-z0-9._/@^~-]*|'')
      echo "render-workflow.sh: refusing to substitute '$v' — it would need quoting in YAML." >&2
      exit 1 ;;
  esac
done

sed \
  -e "s|{{PLUGIN_REPO}}|$PLUGIN_REPO|g" \
  -e "s|{{PLUGIN_REF}}|$PLUGIN_REF|g" \
  -e "s|{{CLAUDE_CODE_VERSION}}|$CLAUDE_CODE_VERSION|g" \
  -e "s|{{NODE_VERSION}}|$NODE_VERSION|g" \
  -e "s|{{TIMEOUT_MINUTES}}|$TIMEOUT_MINUTES|g" \
  "$TEMPLATE"
